vagrant version bump

diff --git a/vagrant/vagrant.SlackBuild b/vagrant/vagrant.SlackBuild
--- a/vagrant/vagrant.SlackBuild
+++ b/vagrant/vagrant.SlackBuild
@@ -1,29 +1,81 @@
 #!/bin/sh
 
 PRGNAM=vagrant
-
-ARCH=${ARCH:-$(uname -m)}
-VERSION=${VERSION:-1.2.7}
+PKGNAM=vagrant
+VERSION=${VERSION:-1.3.3}
 BUILD=${BUILD:-1}
-TAG=${TAG:-rpz}
+TAG=${TAG:-_rpz}
 
-case "$ARCH" in
-  i?86) LIBDIRSUFFIX="" ; ARCH=i386 ;;
-  x86_64) LIBDIRSUFFIX="64" ;;
+case "$(uname -m)" in
+  i?86) DEBARCH="i686" ; LIBDIRSUFFIX="" ; ARCH=i686 ;;
+  x86_64) DEBARCH="x86_64" ; LIBDIRSUFFIX="64" ; ARCH=x86_64 ;;
   *) echo "Package for $(uname -m) architecture is not available." ; exit 1 ;;
 esac
 
 CWD=$(pwd)
-TMP=${TMP:-/tmp/$TAG}
-PKG=$TMP/package-$PRGNAM
+TMP=${TMP:-/tmp/rpz}
+PKG=$TMP/package-$PKGNAM
 OUTPUT=${OUTPUT:-/tmp}
+
+SOURCE="${CWD}/${PRGNAM}-${VERSION}_${ARCH}.deb"
+SRCURL="http://files.vagrantup.com/packages/db8e7a9c79b23264da129f55cf8569167fc22415/${PRGNAM}_${VERSION}_${DEBARCH}.deb"
+
+
+check_installed() {
+    PACKAGE=${1}
+    ls -1 /var/log/packages | grep "^${PACKAGE}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
+    return $?
+}
+
+if [ -e $CWD/slack-required ]; then
+    for REQ in `cat $CWD/slack-required|cut -f 1 -d " "`;do
+        check_installed "$REQ" || {
+           echo "${0##*/}: Required package '$REQ' not installed."
+           exit 1
+       }
+    done
+fi
+
+if [ -e $CWD/slack-conflicts ]; then
+    for REQ in `cat $CWD/slack-conflicts|cut -f 1 -d " "`;do
+        ! check_installed "$REQ" || {
+           echo "${0##*/}: Conflict package '$REQ' was installed."
+           exit 1
+       }
+    done
+fi
+
+
+dnl() {
+    SOURCE=$1
+    SRCURL=$2
+    if [ ! -e $SOURCE ]; then
+       if ! [ "x${SRCURL}" == "x" ]; then
+         echo "Downloading '$(basename ${SOURCE})'."
+         wget --no-check-certificate -nv -T 30 -O "${SOURCE}" "${SRCURL}" || true
+         if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+            echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+            mv -f "${SOURCE}" "${SOURCE}.FAIL"
+            exit 1
+         fi
+         else
+             echo "File '${SOURCE}' not available... aborting the build."
+             exit 1
+         fi
+    fi
+}
+
+dnl $SOURCE $SRCURL
+
+set -eu
+
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $PKG
 
 
-ar p $CWD/vagrant_${VERSION}_$ARCH.deb data.tar.gz | gunzip | tar xv || exit 1
+ar p $SOURCE data.tar.gz | gunzip | tar xv || exit 1
 chown -R root:root .
 chmod -R u+w,go+r-w,a-s .
 
@@ -31,7 +83,10 @@ chmod -R u+w,go+r-w,a-s .
 chmod 0755 .
 
 mkdir -p $PKG/install
-cp $CWD/slack-desc $PKG/install/
+cp -a $CWD/slack-* \
+    $PKG/install/
+
 
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
+
+/sbin/makepkg -l y -c n $OUTPUT/$PKGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
