batch update

diff --git a/freetds/freetds.SlackBuild b/freetds/freetds.SlackBuild
--- a/freetds/freetds.SlackBuild
+++ b/freetds/freetds.SlackBuild
@@ -23,59 +23,98 @@
 #   OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 #   SUCH DAMAGE.
 
-
 PRGNAM=freetds
-PKGNAM=$(basename $0 .SlackBuild)
+PKGNAM=${PKGNAM:-$(basename $0 .SlackBuild)}
 
 INFOFILE="$(pwd)/${PKGNAM}.info"
 if [ -f $INFOFILE ]; then
     source $INFOFILE
 fi
 
-VERSION=${VERSION:-1.2.5}
-BUILD=${BUILD:-1}
+VERSION=${VERSION:-1.2.10}
+BUILD=${BUILD:-2}
 TAG=${TAG:-_rpz}
+PKGTYPE=${PKGTYPE:-txz}
 
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
-    i?86) ARCH=i486 ;;
+    i?86) ARCH=i686 ;;
     arm*) ARCH=arm ;;
        *) ARCH=$( uname -m ) ;;
   esac
 fi
+
+if [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+fi
+
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp/rpz}
 PKG=$TMP/package-$PKGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
+SRCURL=${DOWNLOAD:-http://ftp.freetds.org/pub/${PRGNAM}/stable/${PRGNAM}-${VERSION}.tar.bz2}
+SOURCE="${CWD}/$(basename $SRCURL)"
 
-if [ "$ARCH" = "i486" ]; then
-  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "i686" ]; then
-  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
-  LIBDIRSUFFIX=""
-elif [ "$ARCH" = "x86_64" ]; then
-  SLKCFLAGS="-O2 -fPIC"
-  LIBDIRSUFFIX="64"
-else
-  SLKCFLAGS="-O2"
-  LIBDIRSUFFIX=""
-fi
-
-NUMJOBS=${NUMJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
-
-set -e
 
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
-rm -rf $PRGNAM-$VERSION
-if [ ! -e $CWD/$PRGNAM-$VERSION.tar.gz ]; then
-    wget "ftp://ftp.freetds.org/pub/${PRGNAM}/stable/${PRGNAM}-${VERSION}.tar.gz" -O "$CWD/$PRGNAM-$VERSION.tar.gz"
+rm -rf ${PRGNAM}-${VERSION}
+
+
+check_installed() {
+    PACKAGE=${1}
+    ls -1 /var/log/packages | grep "^${PACKAGE}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
+    return $?
+}
+
+if [ -e $CWD/slack-required ]; then
+    for REQ in `cat $CWD/slack-required|cut -f 1 -d " "`;do
+        check_installed "$REQ" || {
+           echo "${0##*/}: Required package '$REQ' not installed."
+           exit 1
+       }
+    done
 fi
-tar xvf $CWD/$PRGNAM-$VERSION.tar.gz
+
+if [ -e $CWD/slack-conflicts ]; then
+    for REQ in `cat $CWD/slack-conflicts|cut -f 1 -d " "`;do
+        ! check_installed "$REQ" || {
+           echo "${0##*/}: Conflict package '$REQ' was installed."
+           exit 1
+       }
+    done
+fi
+
+dnl() {
+    SOURCE=$1
+    SRCURL=$2
+    if [ ! -e $SOURCE ]; then
+       if ! [ "x${SRCURL}" == "x" ]; then
+         echo "Downloading '$(basename ${SOURCE})'."
+         wget --no-check-certificate -nv -T 30 -O "${SOURCE}" "${SRCURL}" || true
+         if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+            echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+            mv -f "${SOURCE}" "${SOURCE}.FAIL"
+            exit 1
+         fi
+         else
+             echo "File '${SOURCE}' not available... aborting the build."
+             exit 1
+         fi
+    fi
+}
+
+dnl "${SOURCE}" "${SRCURL}"
+
+
+tar -vxjf ${SOURCE}
 cd $PRGNAM-$VERSION
 chown -R root:root .
 find . \
@@ -111,6 +150,9 @@ for i in $PKG/etc/freetds/*.conf ; do mv $i $i.new ; done
 # Remove useless share dir
 rm -rf $PKG/usr/share
 
+# Remove useless doc dir
+rm -rf $PKG/usr/doc/$PKGNAM-$VERSION
+
 find $PKG/usr/man -type f -exec gzip -9 {} \;
 for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
 
@@ -118,13 +160,6 @@ mkdir -p $PKG/usr/doc/$PKGNAM-$VERSION/SlackBuild
 cp -a AUTHORS.md BUGS.md COPYING.txt ChangeLog INSTALL.md NEWS.md README.md TODO.md $PKG/usr/doc/$PKGNAM-$VERSION
 cp -a $CWD/$PRGNAM.SlackBuild $CWD/doinst.sh $CWD/slack-* $PKG/usr/doc/$PKGNAM-$VERSION/SlackBuild
 
-mkdir -p $PKG/install
-cat $CWD/slack-desc > $PKG/install/slack-desc
-cat $CWD/doinst.sh > $PKG/install/doinst.sh
-
-if [ -x "$(which requiredbuilder 2>/dev/null)" ];then
-  requiredbuilder -y -v -s $CWD $PKG
-fi
-
 cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PKGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
+
+/sbin/makepkg -l y -c n $OUTPUT/$PKGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
