mass update

diff --git a/diffuse/diffuse.SlackBuild b/diffuse/diffuse.SlackBuild
--- a/diffuse/diffuse.SlackBuild
+++ b/diffuse/diffuse.SlackBuild
@@ -2,7 +2,7 @@
 
 # Slackware build script for diffuse
 
-# Copyright 2012  MiRacLe.RPZ <miracle@rpz.name>
+# Copyright 2012-2013  MiRacLe.RPZ <miracle@rpz.name>
 # All rights reserved.
 #
 #   Permission to use, copy, modify, and distribute this software for
@@ -25,7 +25,7 @@
 
 PRGNAM=diffuse
 PKGNAM=$(basename $0 .SlackBuild)
-VERSION=${VERSION:-0.4.6}
+VERSION=${VERSION:-0.4.7}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_rpz}
 
@@ -71,11 +71,33 @@ else
   LIBDIRSUFFIX=""
 fi
 
+dnl() {
+    SOURCE=$1
+    SRCURL=$2
+    if [ ! -e $SOURCE ]; then
+       if ! [ "x${SRCURL}" == "x" ]; then
+         echo "Downloading '$(basename ${SOURCE})'."
+         wget --no-check-certificate -nv -T 30 -O "${SOURCE}" "${SRCURL}" || true
+         if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+            echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+            mv -f "${SOURCE}" "${SOURCE}.FAIL"
+            exit 1
+         fi
+         else
+             echo "File '${SOURCE}' not available... aborting the build."
+             exit 1
+         fi
+    fi
+}
+
+
 CWD=$(pwd)
 TMP=${TMP:-/tmp/rpz}
 PKG=$TMP/package-$PKGNAM
 OUTPUT=${OUTPUT:-/tmp}
-SOURCE="http://downloads.sourceforge.net/project/${PRGNAM}/${PRGNAM}/${VERSION}/${PRGNAM}-${VERSION}.tar.bz2"
+SRCURL="http://downloads.sourceforge.net/project/${PRGNAM}/${PRGNAM}/${VERSION}/${PRGNAM}-${VERSION}.tar.bz2"
+SOURCE="${CWD}/${PRGNAM}-${VERSION}.tar.bz2"
+
 
 set -e
 
@@ -84,12 +106,12 @@ mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
 
-if [ ! -e $CWD/${PRGNAM}-${VERSION}.tar.bz2 ]; then
-    wget $SOURCE -O $CWD/${PRGNAM}-${VERSION}.tar.bz2
-fi
+dnl $SOURCE $SRCURL
 
-tar -jxf $CWD/${PRGNAM}-${VERSION}.tar.bz2
+tar -jxf $SOURCE
+
 cd $PRGNAM-$VERSION
+
 chown -R root:root .
 find . \
  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
diff --git a/phpstorm/phpstorm.SlackBuild b/phpstorm/phpstorm.SlackBuild
--- a/phpstorm/phpstorm.SlackBuild
+++ b/phpstorm/phpstorm.SlackBuild
@@ -21,7 +21,7 @@ set -e
 
 PRGNAM=PhpStorm
 PKGNAM=phpstorm
-VERSION=${VERSION:-131.441}
+VERSION=${VERSION:-131.487}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_rpz}
 PKGTYPE=${PKGTYPE:-txz}
@@ -33,8 +33,6 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-SOURCE="http://download.jetbrains.com/webide/$PRGNAM-EAP-$VERSION.tar.gz"
-#SOURCE="http://download.jetbrains.com/webide/PhpStorm-6.0.3.tar.gz"
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp/rpz}
@@ -42,11 +40,38 @@ PKG=$TMP/package-$PKGNAM
 OUTPUT=${OUTPUT:-/tmp}
 
 
+SRCURL="http://download.jetbrains.com/webide/$PRGNAM-EAP-$VERSION.tar.gz"
+SOURCE="${CWD}/${PRGNAM}-${VERSION}.tar.gz"
+#SRCURL="http://download.jetbrains.com/webide/PhpStorm-6.0.3.tar.gz"
+
+
 rm -rf $PKG
 mkdir -p $TMP $PKG $OUTPUT
 
 cd $TMP
 rm -rf ${PRGNAM}-${VERSION}
+
+
+
+dnl() {
+    SOURCE=$1
+    SRCURL=$2
+    if [ ! -e $SOURCE ]; then
+       if ! [ "x${SRCURL}" == "x" ]; then
+         echo "Downloading '$(basename ${SOURCE})'."
+         wget --no-check-certificate -nv -T 30 -O "${SOURCE}" "${SRCURL}" || true
+         if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+            echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+            mv -f "${SOURCE}" "${SOURCE}.FAIL"
+            exit 1
+         fi
+         else
+             echo "File '${SOURCE}' not available... aborting the build."
+             exit 1
+         fi
+    fi
+}
+
 
 if [ "$1" == "netinstall" ]; then
     mkdir -p $PKG/install $PKG/usr/doc/${PKGNAM}-${VERSION}/SlackBuild
@@ -89,18 +114,10 @@ fi
 
 
 
+dnl "$SOURCE" "$SRCURL"
 
-if [ ! -e $CWD/$PRGNAM-EAP-$VERSION.tar.gz ] && [ ! -e $CWD/$PRGNAM-5.0.tar.gz ]; then
-    wget $SOURCE -O $CWD/$PRGNAM-EAP-$VERSION.tar.gz
-fi
+tar zxf $SOURCE
 
-cd $TMP
-
-if [ -f $CWD/$PRGNAM-EAP-$VERSION.tar.gz ]; then
-    tar zxf $CWD/$PRGNAM-EAP-$VERSION.tar.gz
-else
-    tar zxf $CWD/$PRGNAM-5.0.1.tar.gz
-fi
 cd $PRGNAM-$VERSION
 
 chown -R root:root .
