qmmp updated

diff --git a/qmmp/qmmp.SlackBuild b/qmmp/qmmp.SlackBuild
--- a/qmmp/qmmp.SlackBuild
+++ b/qmmp/qmmp.SlackBuild
@@ -22,7 +22,7 @@
 
 PRGNAM=qmmp
 PKGNAM=$(basename $0 .SlackBuild)
-VERSION=${VERSION:-0.7.2}
+VERSION=${VERSION:-0.7.3}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_rpz}
 
@@ -54,9 +54,45 @@ else
   LIBDIRSUFFIX=""
 fi
 
-NUMJOBS=" -j$(lscpu|grep 'CPU(s):'|awk '{print $2 + 1}') "
+NUMJOBS=${NUMJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 
-SOURCE="http://qmmp.ylsoftware.com/files/${PRGNAM}-${VERSION}.tar.bz2"
+SRCURL="http://qmmp.ylsoftware.com/files/${PRGNAM}-${VERSION}.tar.bz2"
+SOURCE="${CWD}/${PRGNAM}-${VERSION}.tar.bz2"
+
+check_installed() {
+    PACKAGE=${1}
+    ls -1 /var/log/packages | grep "^${PACKAGE}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
+    return $?
+}
+
+if [ -e $CWD/slack-required ]; then
+    for REQ in `cat $CWD/slack-required|cut -f 1 -d " "`;do
+        check_installed "$REQ" || {
+           echo "${0##*/}: Required package '$REQ' not installed."
+           exit 1
+       }
+    done
+fi
+
+
+dnl() {
+    SOURCE=$1
+    SRCURL=$2
+    if [ ! -e $SOURCE ]; then
+       if ! [ "x${SRCURL}" == "x" ]; then
+         echo "Downloading '$(basename ${SOURCE})'."
+         wget --no-check-certificate -nv -T 30 -O "${SOURCE}" "${SRCURL}" || true
+         if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+            echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+            mv -f "${SOURCE}" "${SOURCE}.FAIL"
+            exit 1
+         fi
+         else
+             echo "File '${SOURCE}' not available... aborting the build."
+             exit 1
+         fi
+    fi
+}
 
 set -e
 
@@ -71,11 +107,9 @@ mkdir -p $TMP $PKG $OUTPUT
 cd $TMP
 rm -rf $PRGNAM-$VERSION
 
-if [ ! -e $CWD/$PRGNAM-$VERSION.tar.bz2 ]; then
-    wget "${SOURCE}" -O "${CWD}/${PRGNAM}-${VERSION}.tar.bz2"
-fi
+dnl "${SOURCE}" "${SRCURL}"
 
-tar jxf $CWD/$PRGNAM-$VERSION.tar.bz2 || exit 1
+tar jxf $SOURCE || exit 1
 cd $PRGNAM-$VERSION
 
 chown -R root:root .
