icoutils version bump

diff --git a/icoutils/icoutils.SlackBuild b/icoutils/icoutils.SlackBuild
--- a/icoutils/icoutils.SlackBuild
+++ b/icoutils/icoutils.SlackBuild
@@ -20,7 +20,7 @@
 
 PRGNAM=icoutils
 PKGNAM=$(basename $0 .SlackBuild)
-VERSION=${VERSION:-0.30.0}
+VERSION=${VERSION:-0.31.0}
 BUILD=${BUILD:-1}
 TAG=${TAG:-_rpz}
 
@@ -46,7 +46,7 @@ else
   LIBDIRSUFFIX=""
 fi
 
-NUMJOBS=" -j$(lscpu|grep 'CPU(s):'|awk '{print $2 + 1}') "
+NUMJOBS=${NUMJOBS:-$(( $(getconf _NPROCESSORS_ONLN) + 1 ))}
 
 CWD=$(pwd)
 TMP=${TMP:-/tmp/rpz}
@@ -56,18 +56,62 @@ OUTPUT=${OUTPUT:-/tmp}
 set -e
 
 
-SOURCE="http://download.savannah.gnu.org/releases/icoutils/icoutils-0.30.0.tar.bz2"
+SRCURL="http://download.savannah.gnu.org/releases/icoutils/icoutils-${VERSION}.tar.bz2"
+SOURCE="${CWD}/${PRGNAM}-${VERSION}.tar.bz2"
+
+check_installed() {
+    PACKAGE=${1}
+    ls -1 /var/log/packages | grep "^${PACKAGE}-[^-]*-[^-]*-[^-]*$" >/dev/null 2>&1
+    return $?
+}
+
+if [ -e $CWD/slack-required ]; then
+    for REQ in `cat $CWD/slack-required|cut -f 1 -d " "`;do
+        check_installed "$REQ" || {
+           echo "${0##*/}: Required package '$REQ' not installed."
+           exit 1
+       }
+    done
+fi
+
+if [ -e $CWD/slack-conflicts ]; then
+    for REQ in `cat $CWD/slack-conflicts|cut -f 1 -d " "`;do
+        ! check_installed "$REQ" || {
+           echo "${0##*/}: Conflict package '$REQ' was installed."
+           exit 1
+       }
+    done
+fi
+
+dnl() {
+    SOURCE=$1
+    SRCURL=$2
+    if [ ! -e $SOURCE ]; then
+       if ! [ "x${SRCURL}" == "x" ]; then
+         echo "Downloading '$(basename ${SOURCE})'."
+         wget --no-check-certificate -nv -T 30 -O "${SOURCE}" "${SRCURL}" || true
+         if [ $? -ne 0 -o ! -s "${SOURCE}" ]; then
+            echo "Downloading '$(basename ${SOURCE})' failed... aborting the build."
+            mv -f "${SOURCE}" "${SOURCE}.FAIL"
+            exit 1
+         fi
+         else
+             echo "File '${SOURCE}' not available... aborting the build."
+             exit 1
+         fi
+    fi
+}
+
+dnl "${SOURCE}" "${SRCURL}"
+
 
 rm -rf $PKG
 mkdir -p $TMP $PKG
 cd $TMP
 rm -rf $PRGNAM-$VERSION
 
-if [ ! -e $CWD/${PRGNAM}-${VERSION}.tar.bz2 ]; then
-    wget $SOURCE -O $CWD/${PRGNAM}-${VERSION}.tar.bz2
-fi
 
-tar xvf $CWD/$PRGNAM-$VERSION.tar.bz2
+tar xvf $SOURCE
 cd $PRGNAM-$VERSION
 
 # Make sure ownerships and permissions are sane:
@@ -90,7 +134,7 @@ CXXFLAGS="$SLKCFLAGS" \
   --mandir=/usr/man \
   --docdir=/usr/doc/${PKGNAM}-${VERSION} 
 
-make $NUMJOBS 
+make -j$NUMJOBS 
 make DESTDIR=$PKG install-strip
 
 # Compress and link manpages, if any:
